"""initial schema

Revision ID: 8a32d37f649c
Revises: 
Create Date: 2026-08-21 13:35:49.955623
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '8a32d37f649c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetch_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('window_from', sa.DateTime(), nullable=True),
    sa.Column('window_to', sa.DateTime(), nullable=True),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fetch_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fetch_runs_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_runs_status'), ['status'], unique=False)

    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_notice_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('buyer_name', sa.String(length=512), nullable=True),
    sa.Column('buyer_country', sa.String(length=8), nullable=True),
    sa.Column('delivery_location', sa.String(length=512), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_timezone', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('procurement_stage', sa.String(length=32), nullable=True),
    sa.Column('notice_type', sa.String(length=128), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('classification_codes', sa.JSON(), nullable=True),
    sa.Column('document_urls', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('relevance_category', sa.String(length=64), nullable=True),
    sa.Column('relevance_reasons', sa.JSON(), nullable=True),
    sa.Column('topic_relevance_score', sa.Integer(), nullable=False),
    sa.Column('product_fit_score', sa.Integer(), nullable=False),
    sa.Column('procurement_intent_score', sa.Integer(), nullable=False),
    sa.Column('fit_status', sa.String(length=32), nullable=False),
    sa.Column('deployment_fit', sa.String(length=32), nullable=False),
    sa.Column('disqualifiers', sa.JSON(), nullable=True),
    sa.Column('review_flags', sa.JSON(), nullable=True),
    sa.Column('is_actionable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_notice_id', name='uq_tender_source_notice')
    )
    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.create_index('ix_tender_score_deadline', ['relevance_score', 'deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_buyer_country'), ['buyer_country'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_deployment_fit'), ['deployment_fit'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_fit_status'), ['fit_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_is_actionable'), ['is_actionable'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_procurement_stage'), ['procurement_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_publication_date'), ['publication_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_relevance_category'), ['relevance_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_relevance_score'), ['relevance_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenders_status'))
        batch_op.drop_index(batch_op.f('ix_tenders_source'))
        batch_op.drop_index(batch_op.f('ix_tenders_relevance_score'))
        batch_op.drop_index(batch_op.f('ix_tenders_relevance_category'))
        batch_op.drop_index(batch_op.f('ix_tenders_publication_date'))
        batch_op.drop_index(batch_op.f('ix_tenders_procurement_stage'))
        batch_op.drop_index(batch_op.f('ix_tenders_is_actionable'))
        batch_op.drop_index(batch_op.f('ix_tenders_fit_status'))
        batch_op.drop_index(batch_op.f('ix_tenders_deployment_fit'))
        batch_op.drop_index(batch_op.f('ix_tenders_deadline'))
        batch_op.drop_index(batch_op.f('ix_tenders_content_hash'))
        batch_op.drop_index(batch_op.f('ix_tenders_buyer_country'))
        batch_op.drop_index('ix_tender_score_deadline')

    op.drop_table('tenders')
    with op.batch_alter_table('fetch_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fetch_runs_status'))
        batch_op.drop_index(batch_op.f('ix_fetch_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_fetch_runs_source'))

    op.drop_table('fetch_runs')
    # ### end Alembic commands ###
